version: '3.8'

services:
  bandtrack:
    build: .
    container_name: bandtrack
    ports:
      - "3000:3000"
    volumes:
      - bandtrack_bandtrack_data:/app
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    restart: unless-stopped

volumes:
  bandtrack_data:
    external: true
    name: bandtrack_bandtrack_data
