version: '3.8'

services:
  bandtrack:
    build: .
    container_name: bandtrack
    ports:
      - "8080:8080"
    #volumes:
    #  - /volume1/docker/bandtrack/bandtrack.db:/app/bandtrack.db
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    restart: unless-stopped
